"""Professional, self-contained HTML report.

Single file, no external assets, works offline as file:// — using the project's
dark glassmorphism palette so it sits next to the Nexus dashboard visually.
All dynamic content is HTML-escaped to avoid injecting spec-controlled markup.
"""

from __future__ import annotations

import html
from pathlib import Path

from apsec import __version__
from apsec.core.errors import APSecError
from apsec.scanner.models import ScanResult, Severity

# Palette aligned with the project dashboard.
_SEV_COLOR = {
    Severity.CRITICAL: "#ff4444",
    Severity.HIGH: "#ff4444",
    Severity.MEDIUM: "#ffcc00",
    Severity.LOW: "#00d4ff",
    Severity.INFO: "#8a94a6",
}

_CSS = """
:root { --cyan:#00d4ff; --green:#00ff88; --yellow:#ffcc00; --red:#ff4444; --bg:#0b0f17; --card:rgba(255,255,255,.05); }
* { box-sizing:border-box; }
body { margin:0; font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;
  background:radial-gradient(1200px 600px at 20% -10%, #12233b 0%, var(--bg) 60%); color:#e6edf3; padding:32px; }
.wrap { max-width:1000px; margin:0 auto; }
h1 { font-size:24px; margin:0 0 4px; }
h1 span { color:var(--cyan); }
.meta { color:#8a94a6; font-size:13px; margin-bottom:24px; }
.meta code { color:#c9d1d9; }
.cards { display:flex; gap:12px; flex-wrap:wrap; margin-bottom:28px; }
.card { flex:1; min-width:120px; background:var(--card); border:1px solid rgba(255,255,255,.08);
  border-radius:14px; padding:16px 18px; backdrop-filter:blur(8px); }
.card .n { font-size:28px; font-weight:700; }
.card .l { font-size:12px; text-transform:uppercase; letter-spacing:.08em; color:#8a94a6; }
.finding { background:var(--card); border:1px solid rgba(255,255,255,.08); border-left:4px solid #888;
  border-radius:12px; padding:16px 18px; margin-bottom:14px; }
.badge { display:inline-block; font-size:11px; font-weight:700; padding:3px 10px; border-radius:999px;
  color:#0b0f17; margin-right:8px; }
.fid { color:#8a94a6; font-size:12px; font-family:ui-monospace,monospace; }
.ftitle { font-size:16px; font-weight:600; margin:8px 0 6px; }
.loc { font-family:ui-monospace,monospace; font-size:12px; color:var(--cyan); margin-bottom:10px; }
.desc { color:#c9d1d9; line-height:1.5; margin:0 0 10px; }
.fix { background:rgba(0,255,136,.08); border:1px solid rgba(0,255,136,.25); border-radius:8px;
  padding:10px 12px; color:#d7ffe9; font-size:14px; }
.fix b { color:var(--green); }
.refs { margin-top:8px; font-size:12px; }
.refs a { color:var(--cyan); text-decoration:none; word-break:break-all; }
.empty { text-align:center; padding:48px; color:var(--green); font-size:18px; }
footer { margin-top:28px; color:#5b6472; font-size:12px; text-align:center; }
"""


def _badge(sev: Severity) -> str:
    return (
        f'<span class="badge" style="background:{_SEV_COLOR[sev]}">{sev.label}</span>'
    )


def render_html(result: ScanResult) -> str:
    e = html.escape
    counts = result.counts()

    cards = "".join(
        f'<div class="card"><div class="n" style="color:{_SEV_COLOR[s]}">{counts[s.label]}</div>'
        f'<div class="l">{s.label}</div></div>'
        for s in reversed(Severity)
    )

    findings = result.sorted_findings()
    if findings:
        blocks = []
        for f in findings:
            refs = ""
            if f.references:
                links = "".join(
                    f'<div><a href="{e(r)}">{e(r)}</a></div>' for r in f.references
                )
                refs = f'<div class="refs">{links}</div>'
            blocks.append(
                f'<div class="finding" style="border-left-color:{_SEV_COLOR[f.severity]}">'
                f'{_badge(f.severity)}<span class="fid">{e(f.check_id)}</span>'
                f'<div class="ftitle">{e(f.title)}</div>'
                f'<div class="loc">{e(f.location)}</div>'
                f'<p class="desc">{e(f.description)}</p>'
                f'<div class="fix"><b>Fix:</b> {e(f.remediation)}</div>'
                f'{refs}</div>'
            )
        body = "\n".join(blocks)
    else:
        body = '<div class="empty">✔ No issues found by the configured checks.</div>'

    spec = f"OpenAPI {e(result.spec_version)}" if result.spec_version else "n/a"

    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>APSec Report — {e(result.api_title)}</title>
<style>{_CSS}</style></head>
<body><div class="wrap">
<h1>🛡️ APSec <span>Tester</span> — Security Report</h1>
<div class="meta">
  <div><b>{e(result.api_title)}</b></div>
  <div>Target: <code>{e(result.target)}</code> · Spec: {spec} · {e(result.started_at)}</div>
</div>
<div class="cards">{cards}</div>
{body}
<footer>Generated by APSec Tester v{__version__}</footer>
</div></body></html>"""


def write_html(result: ScanResult, path: str | Path) -> Path:
    out = Path(path)
    try:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(render_html(result), encoding="utf-8")
    except OSError as exc:
        raise APSecError(f"Could not write HTML report to {out}: {exc}") from exc
    return out
